### ISSUE TITLE
Changing Fullscreen mode does not change Fullscreen mode

### ISSUE THREAD

**Issue by Krutonium** [PFCKrutonium/OpenRCT2Launcher#34]
Changing the option and hitting apply or okay or both does not change the mode.

(Looking in the Config File, no change is made)

**Comment by Krutonium** [comment]
I just noticed that it made the change after the launcher timed out and closed. Maybe we need to make it able to write out the changes before close?

**Comment by runelaenen** [comment]
When the game itself launches seems the best time?

**Comment by Krutonium** [comment]
Well, when the start button is pressed, ye.

**Comment by FWest98** [comment]
Why don't make it save after hitting OK or Apply?

**Comment by falki147** [comment]
Hmm that's a bug from my code. The new configuration is supposed to be written to a file before the application gets started. I somehow missed it to add. I don't have access to a computer atm so if someone wants fix this it's the same code as line 66-69 in Launcher.vb but instead of LauncherConfig there should be OpenRCT2Config. Just add it after Line 69 and it should work.
